name: NetExec Tests

on:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    name: NetExec Tests for Py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: NetExec set up python on ${{ matrix.os }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: |
        pipx install poetry --python python${{ matrix.python-version }}
        poetry --version
        poetry env info
    - name: Install libraries with dev group
      run: |
        poetry install --with dev
    - name: Run the e2e test
      run: |
        poetry run pytest tests
